### ISSUE TITLE
Error: There was a conflict trying to modify attributes with <edit-config> in plugin cordova-plugin-cloud-settings. The conflicting plugin, undefined, already modified the same attributes

### ISSUE THREAD

**Issue by mwyld** [dpa99c/cordova-plugin-cloud-settings#13]
Was there ever a fix for this? I'm coming across the same issue when I'm building an app on the Ionic platform. It works ok with the `--force` option but would prefer to use it without using this option

_Originally posted by @mwyld in https://github.com/dpa99c/cordova-plugin-cloud-settings/issues/5#issuecomment-522072297_

**Comment by dpa99c** [comment]
As explained in #5, this is an issue with Cordova that cannot be resolved by this plugin itself, which simply [making use of `<edit-config>`](https://github.com/dpa99c/cordova-plugin-cloud-settings/blob/master/plugin.xml#L41) as [documented](https://cordova.apache.org/docs/en/latest/plugin_ref/spec.html#edit-config).

**Comment by therealPaulPlay** [comment]
I'm facing the same issue. Is there something I can do?
