### ISSUE TITLE
Request cloud usage at all

### ISSUE THREAD

**Issue by woodz-** [dpa99c/cordova-plugin-cloud-settings#14]
Is there any possibility to ask the users and let them confirm, whether to use the cloud backend on a specific application at all?

**Comment by dpa99c** [comment]
It's not possible to programmatically disable backup on the Android platform - it's set at manifest level.
However, you can do this in your application logic by simply not calling the plugin or reading the restored cloud data if the user responds "No" to your confirm dialog.
