### ISSUE TITLE
Does plugin still works on ios?

### ISSUE THREAD

**Issue by Senglean** [dpa99c/cordova-plugin-cloud-settings#16]
No error reported, able to save settings but once app in uninstalled there are no settings found for user event after running icloud backup

Also nothing visible in cloudkit dashboard.

Does this plugin still works?

Thanks

- Device details
    - iPhone 11
- OS details
     iOS 13.5.1	
	

- XCode version 11.5

**Comment by dpa99c** [comment]
> Does this plugin still works?

Yes I use it in multiple (iOS &Android) production apps with no problems

Try the [example app](https://github.com/dpa99c/cordova-plugin-cloud-settings-test) and follow the [iOS testing instructions](https://github.com/dpa99c/cordova-plugin-cloud-settings#testing-ios).

**Comment by wiwimaster** [comment]
I'm using the plugin in the latest version and it works like a charm. Both on iOS and Android. Just can second what @dpa99c said, try the example app, it helped me to solve my issues as well.

Also, are you using Cordova or Capacitor (the latter didn't work for me).

**Comment by Senglean** [comment]
thanks I will test and report back

**Comment by Senglean** [comment]
So apparently this plugin is not working if the app is using wkwebview.

in javascript console calling load settings shows the settings but also right after it shows :
Successfully loaded settings: undefined

**Comment by wiwimaster** [comment]
are you getting this message when testing on a real device?

**Comment by Senglean** [comment]
yes the following is in xcode console

Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service

**Comment by wiwimaster** [comment]
hm... I doubt that this has anything to do with the plugin. Do you get this error with the example app, or your app?

**Comment by Senglean** [comment]
in my app..I also confirm that disabling the plugin the xcode error is gone, probably related to wkwebview not being allowed to fetch settings

good to note that now all cordova apps must use wkwebview

**Comment by wiwimaster** [comment]
please try the sample app as recommended above, and see if that works. I
was in your shoes a few weeks ago and it helped me to find my issue (in my
case I used Capacitor instead of Cordova). My app has launched successfully
on the App Store(s) and works without any problem.

best
Jan

Am Do., 4. Juni 2020 um 13:38 Uhr schrieb Senglean <notifications@github.com

**Comment by Senglean** [comment]
but the demo app is not using wkwebview

**Comment by Senglean** [comment]
from cordova 

"Apple will remove UIWebView from their SDK, and developers should migrate to using the WKWebView component starting right now."

so also you will soon encounter this problem

**Comment by wiwimaster** [comment]
Is this about how to migrate from UIWebView to WKWebView (which is no doubt
option-less) or this plugin? I'm just trying to help you and can you tell
my story. And - for completeness - our app runs on WKWebView, you won't
even be able to submit a new app to the app store for testing with
UIWebView.

Am Do., 4. Juni 2020 um 13:43 Uhr schrieb Senglean <notifications@github.com

**Comment by Senglean** [comment]
Also, are you using Cordova or Capacitor (the latter didn't work for me) 

I think it's because capacitor is using wkwebview by default

**Comment by dpa99c** [comment]
I've regression tested the [example project app](https://github.com/dpa99c/cordova-plugin-cloud-settings-test) with [cordova-ios@6](https://github.com/apache/cordova-ios/blob/master/RELEASENOTES.md#600-may-28-2020) (WKWebView-only) on iOS 13.5 building with Xcode 11.5 and I'm satisfied that the plugin is working correctly.

Note that this is a Cordova plugin and as such Capacitor is not a supported environment.
Also not that the iCloud Capability must be added to your iOS app package ID in the Apple Member Centre in order for iCloud backup to work correctly

**Comment by Senglean** [comment]
thanks for confirming working with wkwebview

re icloud capability are you referring to this ?

<img width="1067" alt="Screenshot 2020-06-04 at 12 35 44 PM" src="https://user-images.githubusercontent.com/47624883/83758500-7a815400-a672-11ea-9223-cd9ebe55df83.png">

**Comment by Senglean** [comment]
also i have the following in xcode
<img width="415" alt="Screenshot 2020-06-04 at 2 50 48 PM" src="https://user-images.githubusercontent.com/47624883/83758747-d3e98300-a672-11ea-969d-38f7751ccee4.png">

**Comment by dpa99c** [comment]
yep and then when I uninstall and reinstall the example app via Xcode, a few seconds after running I see the onRestore handler asynchrously invoked as iCloud restores the backup and the data is loaded into the UI:

<img width="300" src="https://user-images.githubusercontent.com/2345062/83760103-6175a480-a66c-11ea-9496-e25888bce120.png" />
