### ISSUE TITLE
Android - cloudSettings.load() never resolve the promise

### ISSUE THREAD

**Issue by ArnaudFelixParis** [dpa99c/cordova-plugin-cloud-settings#18]
Hello,

My problem is only on Android, on iOs it's works perfectly. 
First, I call the `this.cloudSettings.exists()`. The promise respond that I have a settings saved in the cloud.
So I call the `this.cloudSettings.load()`. On iOs no problem, that return me the key-value I previously saved.
But on Android, the promise is never resolved. 
I tried to catch en error, but nothing neither.. 

`this.platform.ready().then(() => {
      if (this.platform.is('mobile')) {
        this.cloudSettings.exists().then((exists: boolean) => {
          console.log('cloudSettingsExist', exists);
          // "exists" equals True
          this.loadSettings();

....

  loadSettings() {
    this.cloudSettings
      .load()
      .then((settings: any) => {
        // never enter here
        console.log('CLOUD settings finded:', settings);
      })
      .catch((error: any) => console.error('FAILED:', error));
  }`

I am doing something wrong ? 

Thank's

**Comment by pslyman** [comment]
I just checked how I've implemented it. Try using `async`, like so:
`.then(async (settings: any) => {`

Otherwise my function is near identical. Do you have a functional `ANDROID_BACKUP_SERVICE_KEY`?

**Comment by dpa99c** [comment]
The [example project](https://github.com/dpa99c/cordova-plugin-cloud-settings-test) works perfectly fine on Android for me when regression testing v2.0.0.
If you are able to reproduce this issue using the example project which is a known codebase, please open a new issue and give full details by completing the issue template.
