### ISSUE TITLE
How much max limit of JSON data?

### ISSUE THREAD

**Issue by natotech** [dpa99c/cordova-plugin-cloud-settings#20]
# Documentation issue
I can't find in the doc how much bytes is the maximum JSON data that can be stored. Is the a max limit? I'm planning to use it to store user data around 10mb. Is that ok?

**Comment by dpa99c** [comment]
https://github.com/dpa99c/cordova-plugin-cloud-settings#ios

> The amount of storage space available is 1MB per user per app.
