### ISSUE TITLE
Add support to browser platform

### ISSUE THREAD

**Issue by tomferreira** [dpa99c/cordova-plugin-cloud-settings#3]
Add support to browser platform.

This will allow for a better experience to emulate app at browser.

Thanks!

**Comment by dpa99c** [comment]
The purpose of this plugin is to store settings in the cloud storage offered by the native mobile platforms (Android & iOS), enabling settings to persist between app installs and across devices. 

I can't think of any equivalent browser platform functionality that could be used to provide/emulate this purpose.
