### ISSUE TITLE
Conflict with phonegap-plugin-push (2.1.3)

### ISSUE THREAD

**Issue by pliablepixels** [dpa99c/cordova-plugin-cloud-settings#5]
Hi, thanks for this library.

It seems this plugin conflicts with `phonegap-plugin-push` (a popular push notification plugin), if installed _after_ `phonegap-plugin-push`. There is no conflict if this plugin is installed _first_ and the push plugin second, which makes me believe its not really a case of conflicting attributes.

**Platform details:**
- version of phonegap-plugin-push: 2.1.3 (thats the latest version cordova-android 7.0 supports)
- cordova version: `8.0.0`
cordova platform version:
```
Installed platforms:
  android 7.0.0
  ios 4.5.5
```

Further, to zero down into the root cause, I created a dummy empty project to make sure its not something else in my real project.

**Error reported when doing:**
`cordova plugin add cordova-plugin-cloud-settings --variable ANDROID_BACKUP_SERVICE_KEY="whatever"` 

```
Failed to install 'cordova-plugin-cloud-settings': Error: There was a conflict trying to modify attributes with <edit-config> in plugin cordova-plugin-cloud-settings. The conflicting plugin, undefined, already modified the same attributes. The conflict must be resolved before cordova-plugin-cloud-settings can be added. You may use --force to add the plugin and overwrite the conflicting attributes.
    at PlatformMunger.add_plugin_changes (/Users/pp/winshare/pp/projects/phonegap/test/platforms/android/cordova/node_modules/cordova-common/src/ConfigChanges/ConfigChanges.js:148:19)
    at /Users/pp/winshare/pp/projects/phonegap/test/platforms/android/cordova/node_modules/cordova-common/src/PluginManager.js:123:29
    at _fulfilled (/Users/pp/winshare/pp/projects/phonegap/test/platforms/android/cordova/node_modules/q/q.js:854:54)
    at self.promiseDispatch.done (/Users/pp/winshare/pp/projects/phonegap/test/platforms/android/cordova/node_modules/q/q.js:883:30)
    at Promise.promise.promiseDispatch (/Users/pp/winshare/pp/projects/phonegap/test/platforms/android/cordova/node_modules/q/q.js:816:13)
    at /Users/pp/winshare/pp/projects/phonegap/test/platforms/android/cordova/node_modules/q/q.js:877:14
    at runSingle (/Users/pp/winshare/pp/projects/phonegap/test/platforms/android/cordova/node_modules/q/q.js:137:13)
    at flush (/Users/pp/winshare/pp/projects/phonegap/test/platforms/android/cordova/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)

(node:27526) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: There was a conflict trying to modify attributes with <edit-config> in plugin cordova-plugin-cloud-settings. The conflicting plugin, undefined, already modified the same attributes. The conflict must be resolved before cordova-plugin-cloud-settings can be added. You may use --force to add the plugin and overwrite the conflicting attributes.
```

This error goes away if I remove push-plugin, install this plugin and add push-plugin back

[This is the plugin.xml](https://github.com/phonegap/phonegap-plugin-push/blob/v2.1.3/plugin.xml) of push-plugin. I don't see any conflicts with what your edit-config is doing. Any thoughts?

**Comment by dpa99c** [comment]
I can reproduce this and it seems to be caused by a bug in the Cordova Android platform scripts: 
I deduce that the triggering factor is the combination of Cordova's own default modifications to the `<application>` element attributes of `AndroidManifest.xml` (e.g. to add app display name from `config.xml`), the modifications to the attributes made by this plugin and the [modifications made to the `<application>` element by `phonegap-plugin-push`](https://github.com/phonegap/phonegap-plugin-push/blob/v2.1.3/plugin.xml#L26).

I tried using the `--force` attribute when adding this plugin after adding `phonegap-plugin-push` and that seemed to work OK:

    cordova plugin add cordova-plugin-cloud-settings --variable ANDROID_BACKUP_SERVICE_KEY="whatever" --force

Not sure I can fix this issue from within this plugin: the only possible solution I can think of would be to write a custom hook script to add the attributes to `AndroidManifest.xml` instead of relying on the provided `<edit-config>` mechanism. Probably best for now to document this as a caveat and provide recommended workarounds.

**Comment by pliablepixels** [comment]
Thanks - I'll give it a shot and report by tomorrow (using `--force`). Any thoughts on why this works if push is installed _after_ this plugin? Would not the same conflict occur?

**Comment by dpa99c** [comment]
> Any thoughts on why this works if push is installed after this plugin? Would not the same conflict occur?

It's dependent on how the Cordova scripts work when adding a new plugin, specifically `cordova-common/src/ConfigChanges/ConfigChanges.js`, but I'm not familiar enough with the internal code to hazard a guess as to why.

**Comment by pliablepixels** [comment]
ok, thanks. I'll close this for now (I haven't tested if `--force` adversely affects any function of push, but it installs)

**Comment by pliablepixels** [comment]
Don't want to open a new issue, but other settings also conflict with this plugin. See [this](https://github.com/phonegap/phonegap-plugin-push/issues/2571#issuecomment-426252908) config change for example. If applied to config.xml, it conflicts with this plugin. I wonder if the rules in this plugin can be changed to make it more specific - I get the feeling its doing something broader than it needs to (not sure exactly what)

**Comment by dpa99c** [comment]
This plugin is [adding the necessary attributes](https://github.com/dpa99c/cordova-plugin-cloud-settings/blob/master/plugin.xml#L41) to the `<application>` element in the `AndroidManifest.xml` using the `<edit-config>` tag in its `plugin.xml`. Without these attributes in place, backup will not work on Android. 

But there appears to be a bug in Cordova when editing attributes of the `<application>` element using `<edit-config>`:

`The conflicting plugin, undefined, already modified the same attributes`

These attributes are necessary and the only other way I can think they could be added would be via a NodeJS hook script to manually edit `AndroidManifest.xml`.

**Comment by pliablepixels** [comment]
So it seems. What a pain. One of the SO solutions seems to be to use one of your other plugins `cordova-custom-config` to make this change (internally via a hook) instead of using `<edit-config>`. Given that this now conflicts with an important `<edit config>` change that involves potential app rejection (the issue I linked to above), I may have to go that route.

**Comment by mwyld** [comment]
Was there ever a fix for this? I'm coming across the same issue when I'm building an app on the Ionic platform. It works ok with the `--force` option but would prefer to use it without using this option
