### ISSUE TITLE
Backup for Android - works in manual mode, not programmatically 

### ISSUE THREAD

**Issue by pliablepixels** [dpa99c/cordova-plugin-cloud-settings#7]
Hi, this may be a function of my lack of how things work on Android:

- I've implemented your plugin in my app. Works like a _charm_ on iOS. Thank you.
- Android - I'm still to wrap my head around things:
- I'm running Android 7

When I try to make a backup programmatically using your plugin, I see

```
 BackupManagerService: dataChanged but no participant pkg='com.pliablepixels.zmninja_pro' uid=10220
```

grepping around, it looks like this is set after the plugin is installed

```
"android:backupAgent": "cordova.plugin.cloudsettings.BackupAgentHelper"
```

However when I do a manual backup using your testing procedure, backup works.

I'm a little lost on what to look far. Any thoughts?

**Comment by dpa99c** [comment]
> When I try to make a backup programmatically using your plugin

How do you mean you are making a backup programmatically using the plugin?

On the Android platform, when you call `save()` it creates a JSON file on disk which is subsequently backed up. On Android 6+ this uses the [Auto Backup](http://androiddoc.qiniudn.com/training/backup/autosyncapi.html) mechanism. The backup process may not take place for several hours - usually when the device is plugged in, connected to Wifi and idle.

However, by following the test procedure you are forcing an immediate backup - something that does not happen on a real user's device.

**Comment by pliablepixels** [comment]
Ah. In the iCloud case, backups were immediate. I did not realize (and did not read) this is how it works in Android. 

So to confirm:

1. On Android 6+, as long as the user has _enabled_ auto backup it looks like all apps have their data backed up, so technically, this plugin is not really needed. Is that correct?

2. On Android < 6, it seems the API key I've generated is used (per your documentation). I just want to make sure that the API key I generate for my app (`com.pliablepixels.zmninja_pro`) doesn't imply customer specific data doesn't get save to a common account - and that each person's data will be separate?

**Comment by dpa99c** [comment]
> On Android 6+, as long as the user has enabled auto backup it looks like all apps have their data backed up, so technically, this plugin is not really needed. Is that correct?

That depends on if you have the [`allowBackup`](https://developer.android.com/guide/topics/manifest/application-element#allowbackup) attribute defined in your `AndroidManifest.xml`. By default in Cordova projects, it's not defined which means everything will get backed up. This may not be what you want as all the Webview storage will also get backed up, which means if you clear values from HTML5 Local Storage/WebSQL/IndexedDB/native SQLite DB, you may find they magically get restored from the cloud backup.

This plugin ensures that only its JSON settings file gets backed up - nothing else.

> On Android < 6, it seems the API key I've generated is used (per your documentation). I just want to make sure that I API key I generate for my app (com.pliablepixels.zmninja_pro) doesn't imply customer specific data doesn't get save to a common account - and that each person's data will be separate?

The [manual Backup API](http://androiddoc.qiniudn.com/training/backup/backupapi.html) stores data per-user per-app (via the API key), so each user's data is stored in against their Google account.

**Comment by pliablepixels** [comment]
Ah perfect. Thanks.
